### ISSUE TITLE
Handle usecase when 10000+ users

### ISSUE THREAD

**Issue by PatelUtkarsh** [thinkatat/at-multiauthor#2]
Currently, in backend edit posts, it slowing down when there are 10000+ users in a site. Handle use case where this plugin works with 10000 users.

**Comment by aagjalpankaj** [comment]
Currently added option `minimumInputLength`. Though this will not be a perfect solution but it will greatly decrease overhead. Thinking to use pagination or ajax here.

Please let me know your thoughts on this.

**Comment by PatelUtkarsh** [comment]
Yep Ajaxify search.

**Comment by aagjalpankaj** [comment]
Added ajax @since 1.0.4.

Thanks @PatelUtkarsh
